### ISSUE TITLE
Form 1 in storybook throws error

### ISSUE THREAD

**Issue by VojtechLunak** [kbss-cvut/s-forms#219]
In the wizard section Domain specific questions, the form will throw error when waiting idle long enough:

_TypeError: options.sort is not a function
    at processTypeaheadOptions (https://deploy-preview-210--s-forms-kbss.netlify.app/690.2b50860d.iframe.bundle.js:2:57342)
    at TypeaheadAnswer (https://deploy-preview-210--s-forms-kbss.netlify.app/690.2b50860d.iframe.bundle.js:2:57997)
..._

**Comment by blcham** [comment]
It seems that it is not working in s-forms-demo app as well.

**Comment by VojtechLunak** [comment]
It seems to work with s-forms version 6.2.0 but not in 6.4.0.
